### ISSUE TITLE
Bad URL in CrudAppUpdateGet.md

### ISSUE THREAD

**Issue by jartis** [hytechclub/web-201#1]
Line 16, change 
```
[...] to hook up `/edit:id` [...]
```
to
```
[...] to hook up `/edit/:id` [...]
```
Otherwise the route cannot be found.

**Comment by hylandtechoutreach** [comment]
Good catch, thanks!

**Comment by hylandtechoutreach** [comment]
Fixed https://github.com/hytechclub/web-201/commit/af1849578ba7d987f3729a798c33ba0eafe658a7
